services:
  postgres_dev:
    image: postgres:16
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: teto_bot_dev 
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:16
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: teto_bot_test
    ports:
      - "5433:5432" # Different port to avoid conflict with dev
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    
  redis_dev:
    image: redis:7
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=dev_password
      - REDIS_AOF_ENABLED=no
      - REDIS_RDB_POLICY=3600#1 300#100 60#10000

volumes:
  postgres_dev_data:
  postgres_test_data:
  redis_dev_data: