defmodule TetoBot.Repo.Migrations.UpdateAccountsForAsh do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Tables already exist, just add any missing indexes/constraints for Ash compatibility

    # Add unique index on users.user_id (for Ash identity) if it doesn't exist
    execute("""
    CREATE UNIQUE INDEX IF NOT EXISTS users_unique_user_id_index
    ON users (user_id)
    """)

    # Add unique index on user_guilds composite key (for Ash identity) if it doesn't exist
    execute("""
    CREATE UNIQUE INDEX IF NOT EXISTS user_guilds_unique_user_guild_index
    ON user_guilds (user_id, guild_id)
    """)
  end

  def down do
    # Only drop the indexes we added, don't touch the tables themselves
    execute("DROP INDEX IF EXISTS user_guilds_unique_user_guild_index")
    execute("DROP INDEX IF EXISTS users_unique_user_id_index")
  end
end
