defmodule TetoBot.Repo.Migrations.ChangeUserDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify(:message_credits, :bigint, default: 30)
    end
  end

  def down do
    alter table(:users) do
      modify(:message_credits, :bigint, default: 10)
    end
  end
end
