defmodule TetoBot.Repo.Migrations.UpdateGuildsForAsh do
  @moduledoc """
  Updates resources based on their most recent snapshots.
  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """
  use Ecto.Migration

  def up do
    # Remove the old primary key constraint from `guild_id` and any dependent foreign keys
    execute("ALTER TABLE guilds DROP CONSTRAINT guilds_pkey CASCADE")

    alter table(:guilds) do
      # Add the new UUID primary key column
      add(:id, :uuid, primary_key: true, default: fragment("gen_random_uuid()"))
    end
  end

  def down do
    # Use raw SQL to modify the column with USING clause
    execute("ALTER TABLE guilds ALTER COLUMN guild_id TYPE bigint USING guild_id::bigint")

    alter table(:guilds) do
      remove(:id)
    end

    # Restore the original primary key constraint
    execute("ALTER TABLE guilds ADD PRIMARY KEY (guild_id)")
  end
end
