defmodule TetoBot.Repo.Migrations.AddUniqToGuildId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:guilds, [:guild_id], name: "guilds_unique_guild_id_index")
  end

  def down do
    drop_if_exists(unique_index(:guilds, [:guild_id], name: "guilds_unique_guild_id_index"))
  end
end
