defmodule TetoBot.Repo.Migrations.AddDailyMessageCount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_guilds) do
      add(:daily_message_count, :bigint, null: false, default: 0)
    end
  end

  def down do
    alter table(:user_guilds) do
      remove(:daily_message_count)
    end
  end
end
